### ISSUE TITLE
when no sub-totals there are also no collapse arrows

### ISSUE THREAD

**Issue by karelv** [nagarajanchinnasamy/subtotal#56]
See here:
http://nagarajanchinnasamy.com/subtotal/examples/280_disable_subtotal.html

(Using google chrome browser)

![image](https://user-images.githubusercontent.com/787006/35516824-08fcca84-050d-11e8-8738-0bfea196d2f5.png)

**Comment by nagarajanchinnasamy** [comment]
This is an expected behaviour. When collapsed, we need to display the subtotal. When subtotal is disabled, what do we have to display?

**Comment by karelv** [comment]
I would expect that I still can collapse... (the arrows are missing for me, as you can see in the screenshot)
Even when there are no sub-totals in the initial view.
Seems we have different understanding of the expected function.
