### ISSUE TITLE
Way to have collapsed as the default?

### ISSUE THREAD

**Issue by tr1ple5** [nagarajanchinnasamy/subtotal#58]
@nagarajanchinnasamy  I would like to thank you for subotal.js.  I do have a requirement where I need to either collapse multiple rows or just have them all collapsed by default.  Currently, I am able to collapse one row, but when we expand that row, the rows inside are automatically expanded as well.  I was hoping there was a way to have the user expand it manually instead of it defaulting to expanded.

Thank you,

Derrick

**Comment by kalimuthu123** [comment]
i want to make collapse at intial refresh
